CREATE TABLE MOVIES(
	MOVIEID VARCHAR2(50) PRIMARY KEY,
	TITLE VARCHAR2(200),
	MYear NUMBER,
	rtAudienceRating VARCHAR2(200),
	rtAudienceNumRatings VARCHAR2(200));

CREATE TABLE MOVIE_GENRES(
    MOVIEID VARCHAR2(50),
    GENRE VARCHAR2(100)
);

CREATE TABLE MOVIE_ACTORS(
	MOVIEID VARCHAR2(50),
	ACTORID VARCHAR2(50),
	ACTORNAME VARCHAR2(100),
	RANKING NUMBER);

CREATE TABLE MOVIE_COUNTRIES(
	MOVIEID VARCHAR2(50),
	COUNTRY VARCHAR2(100));

CREATE TABLE MOVIE_DIRECTORS(
	MOVIEID VARCHAR2(50),
	DIRECTORID VARCHAR2(50),
	DIRECTORNAME VARCHAR2(100));

CREATE TABLE MOVIE_LOCATIONS(
	MOVIEID VARCHAR2(50),
	LOCATION1 VARCHAR2(100),
	LOCATION2 VARCHAR2(100),
	LOCATION3 VARCHAR2(100),
	LOCATION4 VARCHAR2(100));

CREATE TABLE TAGS(
	TAGID VARCHAR2(50),
	VALUE VARCHAR2(100),
	PRIMARY KEY(TAGID));

CREATE TABLE MOVIE_TAGS(
	MOVIEID VARCHAR2(50),
	TAGID VARCHAR2(50),
	TAGWEIGHT NUMBER);


CREATE TABLE USER_RATEDMOVIES(
	userID VARCHAR2(50),
	movieID VARCHAR2(50),
	rating NUMBER,
	date_day NUMBER,
	date_month NUMBER,
	date_year NUMBER,
	date_hour NUMBER,
	date_minute NUMBER,
	date_second NUMBER);

CREATE TABLE USER_RATEDMOVIES_TIMESTAMPS(
	userID VARCHAR2(50),
	movieID VARCHAR2(50),
	rating NUMBER,
	time_stamp timestamp);

CREATE TABLE USER_TAGGEDMOVIES(
	userID VARCHAR2(50),
	movieID VARCHAR2(50),
	tagID VARCHAR2(50),
	date_day NUMBER,
	date_month NUMBER,
	date_year NUMBER,
	date_hour NUMBER,
	date_minute NUMBER,
	date_second NUMBER);

CREATE TABLE USER_TAGGEDMOVIES_TIMESTAMPS(
	userID VARCHAR2(50),
	movieID VARCHAR2(50),
	tagID VARCHAR2(50),
	time_stamp timestamp);


    CREATE INDEX INDGENRE ON MOVIE_GENRES(GENRE);
    CREATE INDEX INDCOUNTRY ON MOVIE_COUNTRIES(COUNTRY);
    CREATE INDEX INDACTOR ON MOVIE_ACTORS(ACTORNAME);
    CREATE INDEX INDDIRECTOR ON MOVIE_DIRECTORS(DIRECTORNAME);

    CREATE INDEX INDUSER ON USER_TAGGEDMOVIES(USERID);
    CREATE INDEX INDTAG ON MOVIE_TAGS(TAGWEIGHT);
    CREATE INDEX INDTAG2 ON MOVIE_TAGS(TAGID);